### ISSUE TITLE
Add IDE files to gitignore

### ISSUE THREAD

**Issue by srv-twry** [NJACKWinterOfCode/IITP-Connect#12]
Add the ide files to .gitignore file

1) `rm -rf .idea`
2)  delete these in `.gitignore`
```
/.idea/workspace.xml
/.idea/libraries
/.idea/misc.xml
```
3) Add this to `.gitignore`
```
.idea
```

Original issue [here](https://github.com/Njack-IITP/IITP-Connect/issues/44)

**Comment by AK-007** [comment]
I'm working on it.
