### ISSUE TITLE
Top coder and URIOJ image not being displayed in some cards in coding calender home activity

### ISSUE THREAD

**Issue by Kartik2016** [NJACKWinterOfCode/IITP-Connect#22]
**Actual Behaviour**
In the coding calender home activity, some cards showing the contests from "Top coder" and "URIOJ" do not have an image. It looks odd.

**Expected Behaviour**
Images should be displayed in the card.

**Steps to reproduce it**
Just click on "Coding calender" in the hamburger menu.

**Screenshots of the issue**
![screenshot_20171210-034311](https://user-images.githubusercontent.com/24453141/33800013-d05d1c64-dd5d-11e7-8545-d63679143201.png)

**Would you like to work on the issue?**
Yes i would like to work on the issue. I think the problem is in the code part that decides which contest is from which site. I can solve it.

**Comment by srv-twry** [comment]
@Kartik2016 Yes i guess you are right. The platform is decided by comparing the domain with hardcoded strings hence the problem.
You can go ahead and work on it.

**Comment by Kartik2016** [comment]
Ok sure.
