### ISSUE TITLE
Use Retrofit instead of Volley to make network requests.

### ISSUE THREAD

**Issue by mayank8318** [NJACKWinterOfCode/IITP-Connect#3]
**Actual Behaviour**

Currently we are using Volley for network requests.

**Expected Behaviour**

Switch to Retrofit for all network requests.

**Comment by Kartik2016** [comment]
I would like to work on this. When can i start ?

**Comment by srv-twry** [comment]
@Kartik2016 You can start anytime.
Here is a brief description of what you have to do:
1.  Setup retrofit for the project i.e adding it into the build.gradle etc.
2.  Edit the code in ```DataScraper``` class in ```CodingCalendar/NetworkUtils``` module to use retrofit instead of volley to fetch the contest data.I believe most of the changes should be made in ```fetchContest``` method.
3. Remove volley from the project's ```build.gradle```.

Contact in case of any queries. :smile:

**Comment by Kartik2016** [comment]
Thank you for providing the description. 
Shall i make a separate package called "service" in the "NetworkUtils" to store the ServiceGenerator and the client class. I believe this will make the organization of the code a bit cleaner.

**Comment by srv-twry** [comment]
@Kartik2016 
Initially when i was working with volley, i thought having separate ```NetworkUtils``` folder for each feature would be better, but i think with ```Retrofit``` it may be tedious. I haven't worked with retrofit so what do you think ?

**Comment by Kartik2016** [comment]
I usually try to keep the UI classes and retrofit network classes in separate folders. The NetworkUtlis folder has  sub folder, one to keep service files and the other to keep the models(POJO). Hence i suggested on making the subfolders. What do you think ?

**Comment by srv-twry** [comment]
I think we should create a new package outside of the ```CodingCalendar``` package and name it ```Retrofit``` and you can create the necessary subfolder for ServiceGenerator and the client class in it.
Then you can delete the ```NetworkUtils``` folder in the ```CodingCalendar``` package.
In this way we can use ```Retrofit``` for network requests in future features also.

**Comment by Kartik2016** [comment]
Yes! This sounds perfect. I'll start working on this.

**Comment by Kartik2016** [comment]
Please review #8
