### ISSUE TITLE
Design the app icon

### ISSUE THREAD

**Issue by srv-twry** [NJACKWinterOfCode/IITP-Connect#6]
**Actual Behaviour**

No app icon exists.

**Expected Behaviour**

App icon should be designed.

Proper discussion about the design and color scheme should be done before working on it.

**Comment by AK-007** [comment]
What design and color scheme you have in mind?

**Comment by Kartik2016** [comment]
I have a design and color scheme in mind. Shall i share a rough idea here ? @srv-twry

**Comment by srv-twry** [comment]
@AK-007 I don't have any specific color scheme in mind. What i meant was that if you have any idea then first discuss it here before working on it.
@Kartik2016 sure, go ahead

**Comment by Kartik2016** [comment]
I have this kind of materialistic logo in mind with minimal branding. Color scheme is flexible, i can be black and white, orange and white, dark blue and gray, or any other as per your suggestion.
![img_20171128_144851054_hdr](https://user-images.githubusercontent.com/24453141/33311756-d79b36de-d44b-11e7-9acd-fd853710a0bc.jpg)

The end points are also circles and the thing beneath the IITP is a usb sign, or it can be left blank too.

**Comment by srv-twry** [comment]
@Kartik2016 I think the central part is fine but the 4 rod shaped extensions don't look that well , on paper atleast. Let's wait for other's view on this .In the meantime any alternatives ?
@chiragw15 @mayank8318 Your views ?

**Comment by Kartik2016** [comment]
Yes, I have one more suggestion.
![img_20171128_154741945_hdr](https://user-images.githubusercontent.com/24453141/33314573-1299f9c0-d454-11e7-92fb-491186b0031a.jpg)
Something in these lines maybe ?

**Comment by srv-twry** [comment]
@Kartik2016 This one looks much better in my view.
Let's wait for others to comment and share their views.

**Comment by Kartik2016** [comment]
Thanks.
Sure!

**Comment by AK-007** [comment]
I had this idea in mind.
With some editing and shading along with a nice color scheme it will look just as required.

![img_20171128_160805](https://user-images.githubusercontent.com/26346816/33315542-f7087ea4-d456-11e7-8ac5-2aaba16ce4f2.jpg)

**Comment by srv-twry** [comment]
@AK-007 Yeah it looks fine too.
Let's wait for some more. We will shortlist 2-3 and then decide which one is most suitable

**Comment by arundhati24** [comment]
I think the one by @AK-007  looks fine.

**Comment by mayank8318** [comment]
The second one by @Kartik2016 looks very standard according to me. First one is ok if we choose a good colour scheme.
The one by @AK-007 is also cool. :+1:

**Comment by AK-007** [comment]
The icon is ready.Should I pull request?
Which one did you finalize?

**Comment by Kartik2016** [comment]
@mayank8318 Shall i design the first one ?

**Comment by srv-twry** [comment]
@AK-007 Yeah you can make a pull request .
@Kartik2016 I think the one by @AK-007 is good so , you can work on other issues :smile:
