### ISSUE TITLE
Set up basic preferences for the coding calendar

### ISSUE THREAD

**Issue by srv-twry** [NJACKWinterOfCode/IITP-Connect#7]
**Actual Behaviour**

There is no ```Settings``` Activity for the coding calendar

**Expected Behaviour**

There should be a ```Settings``` Activity for the coding calendar.

Add a basic ```Settings``` screen for the ```CodingCalendar```. Right now the coding calendar shows contests from all the platforms.
Add the option to choose which platforms to receive contest information about.

**Comment by Kartik2016** [comment]
I'd like to work on this. Apart from the expected behavior given, is there a need to add any other options in the settings ?

**Comment by srv-twry** [comment]
@Kartik2016 No, For now just the option for choosing platforms would be more than sufficient.

**Comment by srv-twry** [comment]
@Kartik2016 updates ?

**Comment by Kartik2016** [comment]
Sorry i got busy with practical exams. I'll submit a PR tommorow evening after the exam.
