### ISSUE TITLE
Fix .gitignore 

### ISSUE THREAD

**Issue by srv-twry** [NJACKWinterOfCode/IITP-Connect#9]
**Actual Behaviour**

The ```.gitignore``` file is not properly configured for the project.

**Expected Behaviour**

Update the file properly.

I think [this](https://github.com/github/gitignore/blob/master/Android.gitignore) can be used a great reference for setting up the ```.gitignore```.

**Comment by Kartik2016** [comment]
Sorry for the initial commits, i made changes on my master branch by mistake.
